export const COUNTRIES = [
  { code: "LB", name: "Lebanon", dialCode: "961" },
  { code: "AE", name: "United Arab Emirates", dialCode: "971" },
  { code: "SA", name: "Saudi Arabia", dialCode: "966" },
  { code: "QA", name: "Qatar", dialCode: "974" },
  { code: "KW", name: "Kuwait", dialCode: "965" },
  { code: "OM", name: "Oman", dialCode: "968" },
  { code: "BH", name: "Bahrain", dialCode: "973" },
  { code: "JO", name: "Jordan", dialCode: "962" },
  { code: "SY", name: "Syria", dialCode: "963" },
  { code: "IQ", name: "Iraq", dialCode: "964" },
  { code: "EG", name: "Egypt", dialCode: "20" },
  { code: "TR", name: "Turkey", dialCode: "90" },
  { code: "GB", name: "United Kingdom", dialCode: "44" },
  { code: "FR", name: "France", dialCode: "33" },
  { code: "DE", name: "Germany", dialCode: "49" },
  { code: "IT", name: "Italy", dialCode: "39" },
  { code: "ES", name: "Spain", dialCode: "34" },
  { code: "NL", name: "Netherlands", dialCode: "31" },
  { code: "BE", name: "Belgium", dialCode: "32" },
  { code: "CH", name: "Switzerland", dialCode: "41" },
  { code: "SE", name: "Sweden", dialCode: "46" },
  { code: "NO", name: "Norway", dialCode: "47" },
  { code: "DK", name: "Denmark", dialCode: "45" },
  { code: "IE", name: "Ireland", dialCode: "353" },
  { code: "PT", name: "Portugal", dialCode: "351" },
  { code: "GR", name: "Greece", dialCode: "30" },
  { code: "PL", name: "Poland", dialCode: "48" },
  { code: "CZ", name: "Czech Republic", dialCode: "420" },
  { code: "AT", name: "Austria", dialCode: "43" },
  { code: "RO", name: "Romania", dialCode: "40" },
  { code: "HU", name: "Hungary", dialCode: "36" },
  { code: "RU", name: "Russia", dialCode: "7" },
  { code: "UA", name: "Ukraine", dialCode: "380" },
  { code: "US", name: "United States", dialCode: "1" },
  { code: "CA", name: "Canada", dialCode: "1" },
  { code: "MX", name: "Mexico", dialCode: "52" },
  { code: "BR", name: "Brazil", dialCode: "55" },
  { code: "AR", name: "Argentina", dialCode: "54" },
  { code: "CL", name: "Chile", dialCode: "56" },
  { code: "CO", name: "Colombia", dialCode: "57" },
  { code: "PE", name: "Peru", dialCode: "51" },
  { code: "VE", name: "Venezuela", dialCode: "58" },
  { code: "ZA", name: "South Africa", dialCode: "27" },
  { code: "NG", name: "Nigeria", dialCode: "234" },
  { code: "KE", name: "Kenya", dialCode: "254" },
  { code: "MA", name: "Morocco", dialCode: "212" },
  { code: "TN", name: "Tunisia", dialCode: "216" },
  { code: "DZ", name: "Algeria", dialCode: "213" },
  { code: "IN", name: "India", dialCode: "91" },
  { code: "PK", name: "Pakistan", dialCode: "92" },
  { code: "BD", name: "Bangladesh", dialCode: "880" },
  { code: "CN", name: "China", dialCode: "86" },
  { code: "JP", name: "Japan", dialCode: "81" },
  { code: "KR", name: "South Korea", dialCode: "82" },
  { code: "SG", name: "Singapore", dialCode: "65" },
  { code: "MY", name: "Malaysia", dialCode: "60" },
  { code: "TH", name: "Thailand", dialCode: "66" },
  { code: "ID", name: "Indonesia", dialCode: "62" },
  { code: "PH", name: "Philippines", dialCode: "63" },
  { code: "AU", name: "Australia", dialCode: "61" },
  { code: "NZ", name: "New Zealand", dialCode: "64" },
];
